# Generated by Django 2.0.7 on 2018-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='my_new_field',
        ),
        migrations.AddField(
            model_name='post',
            name='conten_markup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
