# Generated by Django 2.0.7 on 2018-07-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20180727_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conten_markup',
            new_name='content_markup',
        ),
    ]
